















# if I want to test that a function raises an error
#     with self.assertRaises(ValueError):
#         print_stats()


